name: ootopia_app
description: OOTOPIA App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.15+22

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  camera: ^0.9.4+3
  gallery_saver: ^2.1.0
  flutter_uploader: ^3.0.0-beta.2
  http: ^0.13.3
  rxdart: ^0.27.1
  intl: ^0.17.0
  flutter_dotenv: ^5.0.0
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  loading_overlay: ^0.3.0
  flutter_secure_storage: ^4.2.0
  email_validator: ^2.0.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  percent_indicator: ^3.0.1
  shimmer: ^2.0.0
  geolocator: 8.0.1
  geocoding: ^2.0.0
  image_picker: ^0.8.4+4
  flutter_hooks: ^0.18.0
  video_player: 2.2.6
  provider: ^5.0.0
  flick_video_player: ^0.3.1
  visibility_detector: ^0.2.0
  package_info: ^2.0.2
  multi_select_flutter: ^4.0.0
  url_launcher: ^6.0.7
  permission_handler: ^8.3.0
  photo_manager: ^1.3.10
  receive_sharing_intent: ^1.4.5
  flutter_ffmpeg: ^0.4.0
  amplitude_flutter: ^3.0.0
  sentry_flutter: ^6.1.2
  sqflite: ^2.0.0+3
  shared_preferences: ^2.0.6
  uni_links: ^0.5.1
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  dio: ^4.0.1
  flutter_local_notifications: ^9.2.0
  flutter_tags:
    git:
      url: https://github.com/OOTOPIA/flutter_tags.git
      ref: master
  image_crop: ^0.4.0
  flutter_feather_icons: ^2.0.0+1
  json_annotation: ^4.0.1
  crisp: ^0.2.0
  share_extend: "^2.0.0"
  intl_phone_number_input: ^0.7.0+2
  syncfusion_flutter_sliders: ^19.2.62
  #firebase_dynamic_links: ^2.0.9
  webview_flutter: ^2.0.14
  smart_page_navigation: ^1.1.2
  dotted_border: ^2.0.0+1
  flutter_background_service: ^0.1.5
  wakelock: ^0.5.6
  firebase_messaging: ^11.2.4
  firebase_core: ^1.10.6
  device_info: ^2.0.3
  awesome_notifications: ^0.6.21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.0"
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.5
  json_serializable: ^4.1.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_launcher.png"
  image_path_ios: "assets/icons/icon_launcher_ios.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons_profile/
    - assets/videos/
    - assets/docs/
    - .env
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
