#!/bin/bash
cd ${APPCENTER_SOURCE_DIRECTORY}
# echo "API_URL=${API_URL} 
# AMPLITUDE_KEY=${AMPLITUDE_KEY}" > .env

cat > .env <<EOL
API_URL=${API_URL}
AMPLITUDE_KEY=${AMPLITUDE_KEY}
CRISP_WEBSITE_ID=${CRISP_WEBSITE_ID}
EOL
cat .env